import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Navbar } from "@/components/ui/navbar";
import Link from "next/link";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FlyP2P",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative min-h-screen bg-[#f7f7fb] text-[#0c1018] antialiased`}
      >
        <Providers>
          <div className="pointer-events-none absolute inset-0 overflow-hidden">
            <div className="absolute -top-24 left-1/2 h-72 w-[48rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle,_rgba(72,188,255,0.25),_rgba(247,247,251,0)_60%)] blur-2xl" />
            <div className="absolute bottom-[-20%] right-[-10%] h-[36rem] w-[36rem] rounded-full bg-[radial-gradient(circle,_rgba(177,144,255,0.18),_rgba(247,247,251,0)_60%)] blur-3xl" />
          </div>
          <div className="relative z-10">
            <header className="mx-auto flex w-full items-center justify-between px-6 py-6 sm:px-12">
              <Link href="/" className="text-xl font-semibold text-[#0c1018]">
                FlyP2P
              </Link>
              <div className="hidden sm:block">
                <Navbar />
              </div>
            </header>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
